### ISSUE TITLE
RViz on High-DPI screens

### ISSUE THREAD

**Issue by wxmerkt** [RoboStack/ros-noetic#102] opened 2021-04-09 11:52 UTC
I'm using a high-DPI screen with scaling (4K, 200% scale). Regular RViz works just fine while RoboStack-RViz does not use the full viewport.

This is how RViz starts:
![image](https://user-images.githubusercontent.com/1664508/114175461-f3f06f80-9931-11eb-9c47-876635cd101c.png)

After some window resizing I get this:
![image](https://user-images.githubusercontent.com/1664508/114175584-01a5f500-9932-11eb-968a-b1f2adca4e2f.png)

Sometimes it also renders garbage/background windows in the black space.

Have you observed something similar? Could this be related to a different OGRE version? I use rviz-1.14.5/the latest.

**Comment by lyh458** [comment] 2021-04-10 02:18
I have the same problem as you:
- everything is ok if I drag the edge of RVIZ windows to resize
![](https://cdn.jsdelivr.net/gh/lyh458/ImageRepo@main/1618020716955-1618020716944.png)
- however, if I press the **maximum icon**, problem like you.
![](https://cdn.jsdelivr.net/gh/lyh458/ImageRepo@main/1618020810916-1618020810895.png)
![](https://cdn.jsdelivr.net/gh/lyh458/ImageRepo@main/1618020882033-1618020882025.png)

**Comment by SteveQUT** [comment] 2021-04-12 01:36
Can confirm that I have this issue across multiple machines and on windows. Resizing does appear to fix most case.

**Comment by wolfv** [comment] 2021-04-12 08:46
Thanks all for this bug report! Indeed, it's something I noticed on Fedora, too (and usually fixed by resizing the window).

We have similar issues on OS X where the view is skewed (but the skew factor seems to change based on how wide the RViz Window is).

I wonder if there is a place in RViz where the window viewport width is calculated? cc @rhaschke if you have a pointer where I should look I'd be happy to debug this a bit locally.

**Comment by SteveQUT** [comment] 2021-04-12 10:27
I did a little bit of digging and I am guessing the file is render_widget.cpp in the ogre_helpers folder might be relevant. Seems to have been an issue on High DPI screens here: https://github.com/ros-visualization/rviz/issues/1306#issue-373672105

**Comment by Tobias-Fischer** [comment] 2021-04-12 10:55
How about just calling RenderWidget::resizeEvent() at the end of the RenderWidget constructor? Unfortunately I don't have a high dpi screen to test it.

**Comment by rhaschke** [comment] 2021-04-12 11:13
This issue seems to be a duplicate of https://github.com/ros-visualization/rviz/issues/1262 which was fixed via https://github.com/ros-visualization/rviz/issues/1263. The corresponding commit should be part of the RoboStack-released version as well. @wolfv, have a look at [`render_widget.cpp`](https://github.com/rlober/rviz/blob/bdc4a1848ea5e0cd7bb518977264aaf9cce3c3dc/src/rviz/ogre_helpers/render_widget.cpp#L120-L133)

**Comment by ameysutavani** [comment] 2021-04-25 17:41
I can confirm the same issue on Ubuntu 18.04

**Comment by rhaschke** [comment] 2021-04-25 19:13
@ameysutavani, do you observe this issue with the standard ROS Debian packages as well or with the RoboStack release only?
In the former case, please file a bug report at https://github.com/ros-visualization/rviz.

**Comment by lyh458** [comment] 2021-04-26 01:00
> @ameysutavani, do you observe this issue with the standard ROS Debian packages as well or with the RoboStack release only?
> In the former case, please file a bug report at https://github.com/ros-visualization/rviz.

@rhaschke my system is ubuntu 18.04, and everything of RVIZ (version 1.13.16) with the standard ROS Debian packages (melodic) is ok, but has the same issue after installing this devel with conda.

**Comment by ameysutavani** [comment] 2021-04-26 04:15
> @ameysutavani, do you observe this issue with the standard ROS Debian packages as well or with the RoboStack release only?
> In the former case, please file a bug report at https://github.com/ros-visualization/rviz.

@rhaschke The above issue does not happen with deb install rviz. I can confirm this for both ros melodic and ros noetic

**Comment by Tobias-Fischer** [comment] 2021-06-07 22:51
Hiya, I just had a look at this - it seems like the ogre selector was wrong in https://github.com/RoboStack/ros-noetic/blob/057e616d4d03c4dc23567dd1b82d2add4b7de2d0/patch/ros-noetic-rviz.patch#L101
We use Ogre 1.10 which needs the call to `render_window_->windowMovedOrResized();` which didn't happen without the patch that I just uploaded (@rhaschke).

@ameysutavani @lyh458 @SteveQUT @wxmerkt - let me know if this did the trick for you (the package rebuild will take an hour or so, after that simply `mamba upgrade ros-noetic-rviz`)

**Comment by SteveQUT** [comment] 2021-06-07 23:48
Can confirm this is now fixed on Linux64.

**Comment by SteveQUT** [comment] 2021-11-10 05:18
This appears to have been reintroduced with latest update. 
ros-noetic-rviz           1.14.4           py38h7d895da_3    robostack
![image](https://user-images.githubusercontent.com/40974119/141054320-15455280-a918-42d4-b576-c92db7fb04fc.png)

**Comment by Tobias-Fischer** [comment] 2021-11-10 05:23
Seems like the package was accidentally downgraded rather than upgraded.

**Closed by Tobias-Fischer** 2021-11-10 05:23 UTC
Labels: bug, windows, linux, osx

**Comment by simonbogh** [comment] 2023-02-10 18:42
I experience the view still being skewed using Robostack on macOS Ventura 13.2, Noetic, RViz 1.14.19 (Compiled against Qt version 5.15.6, Compiled against OGRE version 1.10.12 (Xalafu))
<img width="776" alt="1" src="https://user-images.githubusercontent.com/10414639/218172130-5a0723ce-09c5-4137-a150-e42a85d96290.png">
<img width="776" alt="2" src="https://user-images.githubusercontent.com/10414639/218172155-9065bd05-08ec-4249-aa0e-d9e871fcaf9b.png">
