### ISSUE TITLE
issue installing ros-noetic-rviz

### ISSUE THREAD

**Issue by VModugno** [RoboStack/ros-noetic#363] opened 2023-05-12 13:13 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi everyone,

I'm trying to install ros-noetic-rviz but I get this error regarding ogre dependencies:

pkgs/main/linux-64                                            No change
pkgs/main/noarch                                              No change
pkgs/r/linux-64                                               No change
robostack/noarch                                   No change
pkgs/r/noarch                                                 No change
robostack/linux-64                                            No change

Pinned packages:
  - python 3.8.*

Encountered problems while solving:
  - nothing provides ogre >=1.10.12,<1.11.0a0 needed by ros-noetic-rviz-1.14.10-py38h641b9ce_12

thank you for your help

### Installed packages

```shell
# packages in environment at /home/robohikeuser/anaconda3/envs/hori:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.8                h166bdaf_0    conda-forge
ampl-mp                   3.1.0             h2cc385e_1006    conda-forge
anaconda-client           1.11.2             pyhd8ed1ab_0    conda-forge
anaconda-project          0.11.1           py38h06a4308_0  
anyio                     3.5.0            py38h06a4308_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
apr                       1.7.0                hf178f73_5  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py38h7f8727e_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
attr                      2.5.1                h166bdaf_1    conda-forge
attrs                     22.1.0           py38h06a4308_0  
babel                     2.11.0           py38h06a4308_0  
backcall                  0.2.0              pyhd3eb1b0_0  
bcrypt                    3.2.0            py38h5eee18b_1  
beautifulsoup4            4.12.2           py38h06a4308_0  
bleach                    4.1.0              pyhd3eb1b0_0  
boltons                   23.0.0           py38h06a4308_0  
boost                     1.74.0           py38h2b96118_5    conda-forge
boost-cpp                 1.74.0               h75c5d50_8    conda-forge
brotli                    1.0.9                h5eee18b_7  
brotli-bin                1.0.9                h5eee18b_7  
brotlipy                  0.7.0           py38h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.01.10           h06a4308_0  
cairo                     1.16.0            ha61ee94_1014    conda-forge
casadi                    3.5.5           py38h668ca38_18    conda-forge
casadi_kin_dyn            0.0.1                         0    francesco_ruscelli
catkin_pkg                0.5.2              pyhd8ed1ab_0    conda-forge
certifi                   2022.12.7        py38h06a4308_0  
cffi                      1.15.1           py38h5eee18b_3  
chardet                   4.0.0           py38h06a4308_1003  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4            py38h06a4308_0  
clyent                    1.2.2                    py38_1  
cmake                     3.12.2               h52cb24c_0  
comm                      0.1.2            py38h06a4308_0  
conda                     23.3.1           py38h578d9bd_0    conda-forge
conda-build               3.24.0           py38h578d9bd_1    conda-forge
conda-pack                0.6.0              pyhd3eb1b0_0  
conda-package-handling    2.0.2            py38h06a4308_0  
conda-package-streaming   0.7.0            py38h06a4308_0  
conda-verify              3.1.1           py38h578d9bd_1006    conda-forge
console_bridge            1.0.2                h924138e_1    conda-forge
contourpy                 1.0.5            py38hdb19cb5_0  
cryptography              39.0.1           py38h9ce1e76_0  
cycler                    0.11.0             pyhd3eb1b0_0  
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.5.1            py38h295c915_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
distro                    1.5.0              pyhd3eb1b0_1  
docutils                  0.18.1           py38h06a4308_3  
eigen                     3.3.7                hd09550d_1  
empy                      3.3.4              pyh9f0ad1d_1    conda-forge
entrypoints               0.4              py38h06a4308_0  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.5.0                hcb278e6_1    conda-forge
fftw                      3.3.10          nompi_hc118613_107    conda-forge
filelock                  3.9.0            py38h06a4308_0  
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0  
font-ttf-inconsolata      2.001                hcb22688_0  
font-ttf-source-code-pro  2.030                hd3eb1b0_0  
font-ttf-ubuntu           0.83                 h8b1ccd4_0  
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-anaconda            1                    h8fa9717_0  
fonts-conda-ecosystem     1                    hd3eb1b0_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               h4a9f257_0  
future                    0.18.3           py38h06a4308_0  
gettext                   0.21.1               h27087fc_0    conda-forge
giflib                    5.2.1                h5eee18b_3  
glib                      2.76.2               hfc55251_0    conda-forge
glib-tools                2.76.2               hfc55251_0    conda-forge
glob2                     0.7                pyhd3eb1b0_0  
gmock                     1.11.0               hdb19cb5_0  
gmp                       6.2.1                h295c915_3  
gpgme                     1.16.0               h9c3ff4c_0    conda-forge
graphite2                 1.3.14               h295c915_1  
gst-plugins-base          1.21.3               h4243ec0_1    conda-forge
gstreamer                 1.21.3               h25f0c4b_1    conda-forge
gstreamer-orc             0.4.33               h166bdaf_0    conda-forge
gtest                     1.11.0               hdb19cb5_0  
harfbuzz                  6.0.0                h8e241bc_0    conda-forge
horizon                   0.4.5                      py_0    francesco_ruscelli
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4              py38h06a4308_0  
importlib-metadata        6.0.0            py38h06a4308_0  
importlib_metadata        6.0.0                hd3eb1b0_0  
importlib_resources       5.2.0              pyhd3eb1b0_1  
ipopt                     3.14.11              hf9e1ecf_0    conda-forge
ipykernel                 6.19.2           py38hb070fc8_0  
ipython                   8.12.0           py38h06a4308_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
jack                      1.9.22               h11f4161_0    conda-forge
jedi                      0.18.1           py38h06a4308_1  
jinja2                    3.1.2            py38h06a4308_0  
jpeg                      9e                   h5eee18b_1  
json5                     0.9.6              pyhd3eb1b0_0  
jsonpatch                 1.32               pyhd3eb1b0_0  
jsonpointer               2.1                pyhd3eb1b0_0  
jsonschema                4.17.3           py38h06a4308_0  
jupyter_client            8.1.0            py38h06a4308_0  
jupyter_core              5.3.0            py38h06a4308_0  
jupyter_server            1.13.5             pyhd3eb1b0_0  
jupyterlab                3.2.9              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.16.3           py38h06a4308_0  
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py38h6a678d5_0  
krb5                      1.20.1               hf9c8cef_0    conda-forge
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libapr                    1.7.0                hf178f73_5  
libapriconv               1.2.2                h7f8727e_5  
libaprutil                1.6.1                hfefca11_5  
libarchive                3.6.2                hb4bd9a0_1  
libassuan                 2.5.5                h9c3ff4c_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h5eee18b_7  
libbrotlidec              1.0.9                h5eee18b_7  
libbrotlienc              1.0.9                h5eee18b_7  
libcap                    2.66                 ha37c62d_0    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libclang                  15.0.7          default_had23c3d_1    conda-forge
libclang13                15.0.7          default_h3e3d535_1    conda-forge
libcups                   2.3.3                h36d4200_3    conda-forge
libcurl                   7.62.0               h20c2e04_0  
libdb                     6.2.32               h6a678d5_1  
libdeflate                1.17                 h5eee18b_0  
libedit                   3.1.20221030         h5eee18b_0  
libevent                  2.1.10               h9b69904_4    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h6a678d5_6  
libflac                   1.4.2                h27087fc_0    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgcrypt                 1.10.1               h166bdaf_0    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libglib                   2.76.2               hebfc3b9_0    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libgpg-error              1.46                 h620e276_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
liblief                   0.12.3               h6a678d5_0  
libllvm15                 15.0.7               hadd5161_1    conda-forge
libnsl                    2.0.0                h5eee18b_0  
libogg                    1.3.5                h27cfd23_1  
libopenblas               0.3.21               h043d6bf_0  
libopus                   1.3.1                h7b6447c_0  
libosqp                   0.6.2                hcb278e6_4    conda-forge
libpng                    1.6.39               h5eee18b_0  
libpq                     15.1                 h2baec63_3    conda-forge
libqdldl                  0.1.5                h27087fc_1    conda-forge
libsndfile                1.2.0                hb75c966_0    conda-forge
libsodium                 1.0.18               h7b6447c_0  
libsqlite                 3.40.0               h753d276_1    conda-forge
libssh2                   1.10.0               h8f2d780_0  
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libsystemd0               252                  h2a991cd_0    conda-forge
libtiff                   4.5.0                h6a678d5_2  
libtool                   2.4.7                h27087fc_0    conda-forge
libudev1                  253                  h0b41bf4_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.44.2               h5eee18b_0  
libvorbis                 1.3.7                h7b6447c_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
libxcb                    1.13                 h1bed415_1  
libxkbcommon              1.5.0                h79f4944_1    conda-forge
libxml2                   2.10.3               hca2bb57_4    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
log4cxx                   0.11.0               h291d653_3    conda-forge
lz4                       3.1.3            py38h27cfd23_0  
lz4-c                     1.9.4                h6a678d5_0  
markupsafe                2.1.1            py38h7f8727e_0  
matplotlib                3.7.1            py38h578d9bd_0    conda-forge
matplotlib-base           3.7.1            py38h417a72b_1  
matplotlib-inline         0.1.6            py38h06a4308_0  
metis                     5.1.0                hf484d3e_4  
mistune                   0.8.4           py38h7b6447c_1000  
mpg123                    1.31.3               hcb278e6_0    conda-forge
mumps-include             5.2.1               ha770c72_11    conda-forge
mumps-seq                 5.2.1               h2104b81_11    conda-forge
munkres                   1.1.4                      py_0  
mysql-common              8.0.32               h14678bc_0    conda-forge
mysql-libs                8.0.32               h54cf53e_0    conda-forge
nbclassic                 0.5.5            py38h06a4308_0  
nbclient                  0.5.13           py38h06a4308_0  
nbconvert                 6.1.0            py38h06a4308_0  
nbformat                  5.7.0            py38h06a4308_0  
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.5.6            py38h06a4308_0  
netifaces                 0.10.9          py38h27cfd23_1004  
nodejs                    14.20.1              h96d913c_1    conda-forge
nose                      1.3.7           pyhd3eb1b0_1008  
notebook-shim             0.2.2            py38h06a4308_0  
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.89                 he45b914_0    conda-forge
numpy                     1.24.3           py38h59b608b_0    conda-forge
openssl                   1.1.1t               h7f8727e_0  
packaging                 23.0             py38h06a4308_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
paramiko                  2.8.1              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
patch                     2.7.6             h7b6447c_1001  
patchelf                  0.17.2               h6a678d5_0  
pcre2                     10.40                hc3806b6_0    conda-forge
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.4.0            py38h6a678d5_0  
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h7f8727e_1  
pkg-config                0.29.2               h1bed415_8  
pkginfo                   1.9.6            py38h06a4308_0  
pkgutil-resolve-name      1.3.10           py38h06a4308_0  
platformdirs              2.5.2            py38h06a4308_0  
pluggy                    1.0.0            py38h06a4308_1  
ply                       3.11                     py38_0  
poco                      1.11.0               h9c89518_2    conda-forge
pooch                     1.4.0              pyhd3eb1b0_0  
prometheus_client         0.14.1           py38h06a4308_0  
prompt-toolkit            3.0.36           py38h06a4308_0  
psutil                    5.9.0            py38h5eee18b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pulseaudio                16.1                 h4ab2085_1    conda-forge
pure_eval                 0.2.2              pyhd3eb1b0_0  
py-lief                   0.12.3           py38h6a678d5_0  
pybind11                  2.10.4           py38hfbd4bf9_0    conda-forge
pybind11-global           2.10.4           py38hfbd4bf9_0    conda-forge
pycosat                   0.6.4            py38h5eee18b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pycryptodome              3.15.0           py38h276157c_0  
pycryptodomex             3.15.0           py38h5eee18b_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pynacl                    1.5.0            py38h5eee18b_0  
pyopenssl                 23.0.0           py38h06a4308_0  
pyparsing                 3.0.9            py38h06a4308_0  
pyqt                      5.15.7           py38ha0d8c90_3    conda-forge
pyqt5-sip                 12.11.0          py38h8dc9893_3    conda-forge
pyrsistent                0.18.0           py38heee7806_0  
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.15          h257c98d_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2           py38h06a4308_0  
python-gnupg              0.5.0              pyhd8ed1ab_0    conda-forge
python-libarchive-c       2.9                pyhd3eb1b0_1  
python_abi                3.8                      3_cp38    conda-forge
pytz                      2022.7           py38h06a4308_0  
pyyaml                    6.0              py38h5eee18b_1  
pyzmq                     25.0.2           py38h6a678d5_0  
qt-main                   5.15.6               h18908ee_6    conda-forge
readline                  8.2                  h5eee18b_0  
requests                  2.29.0           py38h06a4308_0  
requests-toolbelt         0.9.1              pyhd3eb1b0_0  
rhash                     1.4.1                h3c74f83_1  
ripgrep                   13.0.0               hbdeaff8_0  
ros-distro-mutex          0.2.0                    noetic    robostack
ros-noetic-actionlib      1.13.2          py38h14b2acc_12    robostack
ros-noetic-actionlib-msgs 1.13.1          py38he9ab703_12    robostack
ros-noetic-bond           1.8.6           py38he9ab703_12    robostack
ros-noetic-bond-core      1.8.6           py38he9ab703_12    robostack
ros-noetic-bondcpp        1.8.6           py38hbce7a70_12    robostack
ros-noetic-bondpy         1.8.6           py38he9ab703_12    robostack
ros-noetic-catkin         0.8.10          py38he9ab703_12    robostack
ros-noetic-class-loader   0.5.0           py38ha7d6be6_12    robostack
ros-noetic-cmake-modules  0.5.0           py38he9ab703_12    robostack
ros-noetic-common-msgs    1.13.1          py38he9ab703_12    robostack
ros-noetic-cpp-common     0.7.2           py38haa43186_12    robostack
ros-noetic-diagnostic-msgs 1.13.1          py38he9ab703_12    robostack
ros-noetic-dynamic-reconfigure 1.7.1           py38h14b2acc_12    robostack
ros-noetic-eigenpy        2.6.8           py38hc7ad615_12    robostack
ros-noetic-gencpp         0.6.5           py38he9ab703_12    robostack
ros-noetic-geneus         3.0.0           py38he9ab703_12    robostack
ros-noetic-genlisp        0.4.18          py38he9ab703_12    robostack
ros-noetic-genmsg         0.5.16          py38he9ab703_12    robostack
ros-noetic-gennodejs      2.0.2           py38he9ab703_12    robostack
ros-noetic-genpy          0.6.15          py38hb5abb7c_12    robostack
ros-noetic-geometry-msgs  1.13.1          py38he9ab703_12    robostack
ros-noetic-message-filters 1.15.13         py38h14b2acc_12    robostack
ros-noetic-message-generation 0.4.1           py38he9ab703_12    robostack
ros-noetic-message-runtime 0.4.13          py38he9ab703_12    robostack
ros-noetic-mk             1.15.8          py38he9ab703_12    robostack
ros-noetic-nav-msgs       1.13.1          py38he9ab703_12    robostack
ros-noetic-nodelet        1.10.2          py38h343f6d5_12    robostack
ros-noetic-nodelet-core   1.10.2          py38he9ab703_12    robostack
ros-noetic-nodelet-topic-tools 1.10.2          py38h266acf0_12    robostack
ros-noetic-pinocchio      2.6.3           py38hc7ad615_12    robostack
ros-noetic-pluginlib      1.13.0          py38h3d5e8a6_12    robostack
ros-noetic-ros            1.15.8          py38he9ab703_12    robostack
ros-noetic-ros-base       1.5.0           py38he9ab703_12    robostack
ros-noetic-ros-comm       1.15.13         py38he9ab703_12    robostack
ros-noetic-ros-core       1.5.0           py38he9ab703_12    robostack
ros-noetic-ros-environment 1.3.2           py38he9ab703_12    robostack
ros-noetic-rosbag         1.15.13         py38h14b2acc_12    robostack
ros-noetic-rosbag-migration-rule 1.0.1           py38he9ab703_12    robostack
ros-noetic-rosbag-storage 1.15.13         py38hdab94cb_12    robostack
ros-noetic-rosbash        1.15.8          py38he9ab703_12    robostack
ros-noetic-rosboost-cfg   1.15.8          py38he9ab703_12    robostack
ros-noetic-rosbuild       1.15.8          py38he9ab703_12    robostack
ros-noetic-rosclean       1.15.8          py38he9ab703_12    robostack
ros-noetic-rosconsole     1.14.3          py38hb51d2b2_12    robostack
ros-noetic-rosconsole-bridge 0.5.4           py38hcda8483_12    robostack
ros-noetic-roscpp         1.15.13         py38h14b2acc_12    robostack
ros-noetic-roscpp-core    0.7.2           py38he9ab703_12    robostack
ros-noetic-roscpp-serialization 0.7.2           py38he9ab703_12    robostack
ros-noetic-roscpp-traits  0.7.2           py38he9ab703_12    robostack
ros-noetic-roscreate      1.15.8          py38he9ab703_12    robostack
ros-noetic-rosgraph       1.15.13         py38he9ab703_12    robostack
ros-noetic-rosgraph-msgs  1.11.3          py38he9ab703_12    robostack
ros-noetic-roslang        1.15.8          py38he9ab703_12    robostack
ros-noetic-roslaunch      1.15.13         py38he9ab703_12    robostack
ros-noetic-roslib         1.15.8          py38h14b2acc_12    robostack
ros-noetic-roslisp        1.9.24          py38he9ab703_12    robostack
ros-noetic-roslz4         1.15.13         py38he9ab703_12    robostack
ros-noetic-rosmake        1.15.8          py38he9ab703_12    robostack
ros-noetic-rosmaster      1.15.13         py38he9ab703_12    robostack
ros-noetic-rosmsg         1.15.13         py38he9ab703_12    robostack
ros-noetic-rosnode        1.15.13         py38he9ab703_12    robostack
ros-noetic-rosout         1.15.13         py38he9ab703_12    robostack
ros-noetic-rospack        2.6.2           py38h3d5e8a6_12    robostack
ros-noetic-rosparam       1.15.13         py38he9ab703_12    robostack
ros-noetic-rospy          1.15.13         py38he9ab703_12    robostack
ros-noetic-rosservice     1.15.13         py38he9ab703_12    robostack
ros-noetic-rostest        1.15.13         py38h14b2acc_12    robostack
ros-noetic-rostime        0.7.2           py38h14b2acc_12    robostack
ros-noetic-rostopic       1.15.13         py38he9ab703_12    robostack
ros-noetic-rosunit        1.15.8          py38he9ab703_12    robostack
ros-noetic-roswtf         1.15.13         py38he9ab703_12    robostack
ros-noetic-sensor-msgs    1.13.1          py38he9ab703_12    robostack
ros-noetic-shape-msgs     1.13.1          py38he9ab703_12    robostack
ros-noetic-smclib         1.8.6           py38he9ab703_12    robostack
ros-noetic-std-msgs       0.5.13          py38he9ab703_12    robostack
ros-noetic-std-srvs       1.11.3          py38he9ab703_12    robostack
ros-noetic-stereo-msgs    1.13.1          py38he9ab703_12    robostack
ros-noetic-tf2-msgs       0.7.5           py38he9ab703_12    robostack
ros-noetic-topic-tools    1.15.13         py38he9ab703_12    robostack
ros-noetic-trajectory-msgs 1.13.1          py38he9ab703_12    robostack
ros-noetic-visualization-msgs 1.13.1          py38he9ab703_12    robostack
ros-noetic-xmlrpcpp       1.15.13         py38h14b2acc_12    robostack
rosdep                    0.22.2             pyhd8ed1ab_0    conda-forge
rosdistro                 0.9.0            py38h578d9bd_0    conda-forge
rospkg                    1.5.0              pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.21          py38h5eee18b_0  
ruamel.yaml.clib          0.2.6            py38h5eee18b_1  
ruamel_yaml               0.17.21          py38h5eee18b_0  
sbcl                      1.5.4                ha770c72_1    conda-forge
scipy                     1.10.1           py38h59f1b5f_0    conda-forge
scotch                    6.0.9                hb2e6521_2    conda-forge
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                66.0.0           py38h06a4308_0  
sip                       6.7.9            py38h17151c0_0    conda-forge
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.2.0            py38h06a4308_1  
soupsieve                 2.4              py38h06a4308_0  
stack_data                0.2.0              pyhd3eb1b0_0  
terminado                 0.17.1           py38h06a4308_0  
testpath                  0.6.0            py38h06a4308_0  
tinyxml                   2.6.2                h4bd325d_2    conda-forge
tinyxml2                  9.0.0                h9c3ff4c_2    conda-forge
tk                        8.6.12               h1ccaba5_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1            py38h06a4308_0  
toolz                     0.12.0           py38h06a4308_0  
tornado                   6.2              py38h5eee18b_0  
tqdm                      4.65.0           py38hb070fc8_0  
traitlets                 5.7.1            py38h06a4308_0  
typing-extensions         4.5.0            py38h06a4308_0  
typing_extensions         4.5.0            py38h06a4308_0  
unixodbc                  2.3.11               h5eee18b_0  
urdfdom                   2.3.5                h4bd325d_0    conda-forge
urdfdom_headers           1.1.0                h924138e_0    conda-forge
urllib3                   1.26.15          py38h06a4308_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1                    py38_1  
websocket-client          0.58.0           py38h06a4308_4  
wheel                     0.38.4           py38h06a4308_0  
xcb-util                  0.4.0                h166bdaf_0    conda-forge
xcb-util-image            0.4.0                h166bdaf_0    conda-forge
xcb-util-keysyms          0.4.0                h166bdaf_0    conda-forge
xcb-util-renderutil       0.3.9                h166bdaf_0    conda-forge
xcb-util-wm               0.4.1                h166bdaf_0    conda-forge
xkeyboard-config          2.38                 h0b41bf4_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.8.4                h0b41bf4_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h27cfd23_1007  
xz                        5.2.10               h5eee18b_1  
yaml                      0.2.5                h7b6447c_0  
yaml-cpp                  0.7.0                h27087fc_2    conda-forge
zeromq                    4.3.4                h2531618_0  
zipp                      3.11.0           py38h06a4308_0  
zlib                      1.2.13               h166bdaf_4    conda-forge
zstandard                 0.19.0           py38h5eee18b_0  
zstd                      1.5.5                hc292b87_0
```

### Environment info

```shell
active environment : hori
    active env location : /home/robohikeuser/anaconda3/envs/hori
            shell level : 2
       user config file : /home/robohikeuser/.condarc
 populated config files : 
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __cuda=12.0=0
                          __linux=5.19.0=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/robohikeuser/anaconda3  (writable)
      conda av data dir : /home/robohikeuser/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/robohikeuser/anaconda3/pkgs
                          /home/robohikeuser/.conda/pkgs
       envs directories : /home/robohikeuser/anaconda3/envs
                          /home/robohikeuser/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Linux/5.19.0-41-generic ubuntu/22.04.2 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by traversaro** [comment] 2023-05-12 13:19
Hi @VModugno! I am not sure which instructions are you following, but you need to use the `robostack-staging` channel, not the `robostack` one. Furthermore, it seems that you are using an `anaconda` install, instead of a `mambaforge` install, do you have any reason for using `anaconda` ? If you do not any specific reason, I suggest you do uninstall `anaconda` and install `mambaforge`.

If for any reason you neeed to use anaconda, no problem, but pay attention that you need to install robostack using the `robostack-staging` and `conda-forge` channel, and pay attention to avoid the use of the `defaults` channel.

**Comment by VModugno** [comment] 2023-05-12 13:28
Hi Silvio,
thank you for the quick reply! I'm currently trying to use the horizon package and I have been using the environment.yml from this [link](https://github.com/ADVRHumanoids/horizon). Should I switch the channel to robostack-staging and install at least all the robostack dependencies using mamba instead of conda? is that right?
thank you for your help

**Comment by traversaro** [comment] 2023-05-12 14:19
Actually it seems that you successfully installed ros via the old `robostack` channel, so that worked out fine. So, while you could experience problems with the old packages contaned in `robostack`, the  specific problem seems something else. Can you clarify the **exact** command are you executing to install ` ros-noetic-rviz` ? From the output it seems that for some reason it is not considering the `conda-forge` channel.

**Comment by VModugno** [comment] 2023-05-12 14:28
in order to install it I just did  mamba install -y ros-noetic-rviz -c robostack. I did try with conda as well and I tried by switching the channel to robostack-staging

**Comment by traversaro** [comment] 2023-05-12 15:16
The problem is that apparently in your environment conda-forge is not configured as a channel to use (a consequence of using anaconda instead of mambaforge, hence my original comment). If you want to install robostack software, you always need to also specify the conda-forge channel, as all the non-ROS dependencies come from there.

I think that:

~~~
mamba install -y ros-noetic-rviz -c robostack -c conda-forge 
~~~

should work fine in your exising environment (for new environments, please use `robostack-staging`).

**Comment by VModugno** [comment] 2023-05-12 15:25
I see thank you Silvio, everything is clear now. that's great because robostack is an amazing tool for what we are doing now and I have just started to use it. Right now I'm in contact with Francesco and he is instructing me on how to proceed for a proper installation of their package. Thank you again for your help!

**Comment by traversaro** [comment] 2023-05-12 16:25
If everything is solved, feel free to close the issue, thanks!

**Closed** 2023-05-12 20:14 UTC
Labels: bug
